//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescalificacionesM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Pruebas = new HashSet<Prueba>();
        }
    
        public int EventoID { get; set; }
        public string Distancia { get; set; }
        public int RamaID { get; set; }
        public int CategoriaID { get; set; }
        public int EstiloID { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Estilo Estilo { get; set; }
        public virtual Rama Rama { get; set; }
        public virtual ICollection<Prueba> Pruebas { get; set; }
    }
}
