//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescalificacionesM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heat
    {
        public int HeatID { get; set; }
        public string Descripcion { get; set; }
        public int PruebaID { get; set; }
    
        public virtual Prueba Prueba { get; set; }
    }
}
