//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescalificacionesM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nadador
    {
        public int NadadorID { get; set; }
        public string Nombre { get; set; }
        public int HeatID { get; set; }
        public int DescalificacionID { get; set; }
    
        public virtual Descalificacion Descalificacion { get; set; }
    }
}
