//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescalificacionesM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        public Prueba()
        {
            this.Heats = new HashSet<Heat>();
        }
    
        public int PruebaID { get; set; }
        public int CompetenciaID { get; set; }
        public int EventoID { get; set; }
    
        public virtual Competencia Competencia { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual ICollection<Heat> Heats { get; set; }
    }
}
